######################################################################
##
## Filename: test_dff_preload_reg1.udo
## Created on: Tue Oct 20 20:09:15 中国标准时间 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
