######################################################################
##
## Filename: test_complex_multiplier.udo
## Created on: Tue Oct 27 16:47:32 中国标准时间 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
