######################################################################
##
## Filename: test_partial_product.udo
## Created on: Tue Oct 13 16:26:43 中国标准时间 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
